### PR TITLE
Attempted to make Windows-compatible.

### PR DESCRIPTION
**Pull request by bensenderling**
I attempted to make the built Windows -compatible. The changes ended up being fairly minor. I'm not sure if the change to skdh\io\_extensions\read_geneactive.c would make it MacOS-incompatible. I was able to build this on Windows and run the methods through MATLAB. I also added an example.m file with example code.

### CODE REVIEW

**Comment by LukasAdamowicz** [comment]
were you able to compile this on windows? the only changes that might effect that are the adding of libraries in the C-code

**Comment by LukasAdamowicz** [comment]
I made a few changes, can you confirm that these are still working on windows?

**Comment by bensenderling** [comment]
It's still building and installing on Windows. I'm not sure if the use of #define timegm _mkgmtime in read_genactive.c would also make it incompatible with macOS.

**Comment by LukasAdamowicz** [comment]
took some changes and incorporated, but going to close this PR

**Pull request closed without merging**
